[tool.poetry]
name = "twitch-highlighter"
version = "0.1.0"
description = ""
authors = ["porplax <saynemarsh9@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
